ruby
source "https://rubygems.org"
ruby '3.0.0'
gem 'rspec'
gem 'pry'
gem 'rubocop'
gem 'awesome_print'
gem 'pry'
gem 'pry-byebug'
gem 'pry-doc'
gem 'pry-rails'
gem 'pry-rescue'
gem 'pry-theme'
gem 'pry-stack_explorer'
gem 'binding_of_caller'
gem 'dotenv'